name: Make sure readme doesnt say stipe
on:
  push:
    branches:    
      - 'main'
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          set +e
          grep -i 'stipe' README.md
          test $? -eq 1
